sudo: false

language: go
go:
  - "1.11"
  - "1.x"
env:
- GO111MODULE=on

services:
  - redis-server
  - memcached

before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -cover ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false