[[constraint]]
  name = "github.com/cactus/go-statsd-client"
  version = "3.1.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "^6.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/gomemcache"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.0"
